# Generated by Django 3.0.5 on 2021-09-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pesan',
            field=models.CharField(max_length=200),
        ),
    ]
